config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users
  root to: 'pages#home'
  resources :categories, only: :index do
    resources :pieces, only: :create
  end
  resources :pieces, only: [:index, :show, :edit, :update, :destroy] do
    resources :orders, only: :create
  end

  resources :orders, only: :show

  resources :parts, only: [:create, :update]

  post "/pieces", to: "pieces#clone"
  get "/dashboard", to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :pieces, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :piece

  enum progress: { pending: 0, accepted: 1, refused: 2, delivered: 3 }
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :piece

  enum color: { black: 0, white: 1, raw: 2, red: 3, blue: 4, grey: 5, light: 6 }
  enum material: { pine: 0, oak: 1,  beech: 2, teak: 3, steel: 4, inox: 5 }
  enum shape: { round: 0, square: 1, rectangular: 2 }
  enum position: { top: 0, bottom: 1 }

  def translated_color
    case color
    when "black" then "Noir"
    when "white" then "Blanc"
    when "raw" then "Nature"
    when "red" then "Rouge"
    when "blue" then "Bleu"
    when "grey" then "Gris"
    when "light" then "Clair"
    end
  end

  def translated_material
    case material
    when "pine" then "Pin"
    when "oak" then "Chêne"
    when "beech" then "Hêtre"
    when "teak" then "Teck"
    when "steel" then "Acier"
    when "inox" then "Inox"
    end
  end

  def translated_shape
    case shape
    when "round" then "Rond"
    when "square" then "Carré"
    when "rectangular" then "Rectangulaire"
    end
  end
end

app/models/piece.rb
class Piece < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :parts, dependent: :destroy
  has_many :orders, dependent: :destroy

  has_one_attached :photo

  def create_parts
    if category.title == "table" && parts.empty?
      parts.build(piece: self, color: 4, height: 10, width: 100, length: 160, material: 2, shape: 1, position: 0).save
      parts.build(piece: self, color: 2, height: 0, width: 6, length: 60, material: 2, shape: 0, position: 1).save
  end
end

  def json_params
    top_part = self.parts.find_by(position: 0)
    bottom_part = self.parts.find_by(position: 1)
    return {
      category: self.category.title,
      topPart: {
        shape: top_part.shape,
        width: top_part.width,
        height: top_part.height,
        length: top_part.length,
        color: top_part.color
      },
      bottomPart: {
        shape: bottom_part.shape,
        topRadius: bottom_part.width,
        bottomRadius: bottom_part.width,
        lengthCylinder: bottom_part.length,
        topWidth: top_part.width,
        topHeight: top_part.height,
        topLength: top_part.length,
        color: bottom_part.color
      }
    }
  end

  def clone_with_associations
    new_piece = self.dup
    self.parts.each do |part|
      new_part = part.dup
      new_piece.parts << new_part
      new_part.save
    end
    new_piece.save
    new_piece
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pieces
  has_many :orders
  has_many :parts, through: :pieces

  enum role: { craftman: 0, client: 1 }
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # ligne ci-dessous a enlever !!!!!!!!!!!!!!! ONLY FOR TESTS PURPOSES
  skip_before_action :authenticate_user!, only: :show
  # ligne ci-dessus a enlever !!!!!!!!!!!!!!!

  def create
    @order = Order.new(progress: 0)
    @order.user_id = current_user.id
    @order.piece_id = params[:piece_id]
    if @order.save
      redirect_to order_path(@order)
    else
      redirect_to edit_piece_path(params[:piece_id])
    end
  end

  def show
    @order = Order.find(params[:id])
    @top = @order.piece.parts.find_by_position(0)
    @bottom = @order.piece.parts.find_by_position(1)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @categories = Category.all
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:create]

  def update
    @part = Part.find(params[:id])
    @part.update(part_params)
    redirect_to edit_piece_path(@part.piece, editable: true)
  end

  private

  def part_params
    params.require(:part).permit(:color, :height, :width, :length, :material, :shape, :position, :piece_id, :volume_json)
    # ADD VOLUME
  end
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :edit]

  def index
    @pieces = Piece.joins(:category, :orders).where(sql_query, query: "#{params[:query]}")
  end

  def show
    @piece = Piece.find(params[:id])
    @top = @piece.parts.find_by_position(0)
    @bottom = @piece.parts.find_by_position(1)
    @editable = !params['editable'].nil?
  end

  def create
    @piece = Piece.new(name: "Votre meuble n°#{current_user.pieces.count + 1}")
    @user = current_user
    @piece.user = @user
    @category = Category.find(params[:category_id]) #Faire le lien entre piece et category grâce à la modal (cf: methode de l'index)
    @piece.category = @category
    if @piece.save
      @piece.create_parts
      redirect_to edit_piece_path(@piece)
    else
      render :index
    end
  end

  def edit
    @piece = Piece.find(params[:id])
    @part_top = @piece.parts.find_by(position: 0)
    @part_bottom = @piece.parts.find_by(position: 1)
  end

  def update
    @piece = Piece.find(params[:id])
    # @part_top = @piece.parts.find_by(position: 0)
    # @part_bottom = @piece.parts.find_by(position: 1)
    # @part_top = @part_top.update
    # @part_bottom = @part_bottom.update
    if @piece.update(piece_params)
      redirect_to piece_path(@piece, editable: true)
    else
      @part_top = @piece.parts.find_by(position: 0)
      @part_bottom = @piece.parts.find_by(position: 1)
      render :edit
    end
  end

  def destroy
    @piece = Piece.find(params[:id])
    @piece.destroy
    redirect_to dashboard_path
  end

  def clone
    @piece = Piece.find(params[:id])
    @copy_piece = @piece.clone_with_associations

    # @part_top = @copy_piece.parts.find_by(position: 0)
    # @part_bottom = @copy_piece.parts.find_by(position: 1)
    redirect_to edit_piece_path(@copy_piece)
  end

  private

  def sql_query
    " \
    categories.title ILIKE :query \
    AND orders.progress = 3 \
    "
  end

  def piece_params
    params.require(:piece).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @pieces = current_user.pieces
    @parts = current_user.parts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= yield :head %>
  </head>

  <body>
    <% if content_for?(:navbar) %>
      <%= yield :navbar %>
    <% else %>
    <%= render 'shared/navbar' %>
    <% end %>
    
    <%= render 'shared/flashes' %>

    <%= yield %>

    <% if content_for?(:footer) %>
      <%= yield :footer %>
    <% else %>
    <%= render 'shared/footer' %>
    <% end %>
  </body>
</html>

app/views/orders/show.html.erb
<div class="container">

  <div class="d-flex justify-content-between align-items-end mt-3">
    <h1>Commande #<%= @order.id %></h1>
    <%= link_to root_path, :class => "home-btn" do %>
        <i class="fas fa-home"></i>
    <% end %>
  </div>

  <div class="cont-all mt-3 d-flex justify-content-between">
    <div class="card-img-show">
      <% if @order.piece.photo.attached? %>
        <%= cl_image_tag @order.piece.photo.key, :width=>500, :height=>350, :crop=>"fill", class: "card-img-top zoom"%>
      <% else %>
        <%= cl_image_tag "mv2lqq", :width=>500, :height=>350, :crop=>"fill", class: "card-img-top zoom"%>
      <% end %>
    </div>
    <div class="card-inner pl-3 mx-5">
      <h2 class="pb-2"><%= @order.piece.name.capitalize %></h2>
      <div class="inner-desc my-3"><em>Caractéristiques de votre table :</em></div>
        <div class="inner-text d-flex justify-content-around">
          <div class="mt-3">
            <p><strong>Plateau :</strong></p>
            <p><u>Couleur :</u> <%= @top.translated_color %><br>
              <u>Dimension :</u> <%= @top.length %>x<%= @top.width %>x<%= @top.height %><br>
              <u>Matériau :</u> <%= @top.translated_material %><br>
              <u>Forme :</u> <%= @top.translated_shape %></p>
          </div>
          <div class="mt-3">
            <p><strong>Pieds :</strong></p>
            <p><u>Couleur :</u> <%= @bottom.translated_color %><br>
              <u>Dimension :</u> <%= @bottom.length %>x<%= @bottom.width %>x<%= @bottom.height %><br>
              <u>Matériau :</u> <%= @bottom.translated_material %><br>
              <u>Forme :</u> <%= @bottom.translated_shape %></p>
          </div>
        </div>
    </div>
  </div>

  <div class="cont-progress py-3 mt-3">
    <ul class="progressbar">
      <li>En attente de confirmation</li>
      <li>En cours de fabrication</li>
      <li>Expédiée</li>
      <li>Livrée</li>
    </ul>
  </div>

</div>

app/views/pages/home.html.erb
<!-- <div id="coco" data-coco-params="<%= {email: User.last.email}.to_json %>"></div> -->


 <% content_for :navbar do %>
      <%= render 'shared/navbar_home' %>
 <% end %>
<%= render 'shared/banner' %>

<div class="container mt-4 py-4">
  <div class="row">
    <div class="col-3 d-flex align-items-stretch">
      <div class="card rounded-0" style="width: 18rem;">
        <div class="card-img-top text-center pt-4">
          <%=image_tag("blueprint.svg")%>
        </div>
          <div class="card-body">
            <p class="card-text text-center">Imaginez votre meuble</p>
          </div>
      </div>
    </div>

    <div class="col-3 d-flex align-items-stretch">
      <div class="card rounded-0" style="width: 18rem;">
        <div class="card-img-top text-center pt-4">
          <%=image_tag("geometry.svg")%>
        </div>
          <div class="card-body">
            <p class="card-text text-center">Modélisez-le facilement</p>
          </div>
      </div>
    </div>

    <div class="col-3 d-flex align-items-stretch">
      <div class="card rounded-0" style="width: 18rem;">
        <div class="card-img-top text-center pt-4">
          <%=image_tag("settings.svg")%>
        </div>
          <div class="card-body">
            <p class="card-text text-center">Un artisan produit votre création</p>
          </div>
      </div>
    </div>

    <div class="col-3 d-flex align-items-stretch">
      <div class="card rounded-0" style="width: 18rem;">
        <div class="card-img-top text-center pt-4">
          <%=image_tag("armchair.svg")%>
        </div>
          <div class="card-body">
            <p class="card-text text-center">Livré directement chez vous</p>
          </div>
      </div>
    </div>
  </div>
</div>

<div class="container py-4">
  <div class="cards">

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(https://static.turbosquid.com/Preview/2019/03/19__04_10_54/industrial_table_00.jpg5B321C05-F279-48C2-AFEE-5F9E0EE4BB76Zoom.jpg)">
      <%= link_to "Tables", pieces_path(query: "table"), class: "btn btn-ghost" %>
    </div>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(https://media.madeindesign.com/nuxeo/products/c/a/bibliotheque-mikado-large-rouge_madeindesign_74145_original.jpg)">
      <%= link_to "Etagères", pieces_path(query: "étagères") , class: "btn btn-ghost" %>
    </div>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(https://cdn.conforama.fr/prod/product/image/38d2/G_CNF_I52807871_B.jpeg)">
      <%= link_to "Commodes", pieces_path(query: "commode"), class: "btn btn-ghost" %>
    </div>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(https://www.made-in-meubles.com/media/catalog/product/optimized/2/e/2ea75696a4d7e9b6182055f87ecaaffc/bt0200a-meubletv-dessus.jpg">
      <%= link_to "Meubles TV", pieces_path(query: "meuble tv"), class: "btn btn-ghost" %>
    </div>
  </div>
</div>

<% content_for :head do %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<% end %>

app/views/pieces/_data-set.html.erb
<div id="shape-top" data-shape-top-params="<%= {shapeTop: selectedOptions[0].innerHTML}.to_json %>"></div>

<div id="color-top" data-color-top-params="<%= {colorTop: selectedOptions[0].innerHTML}.to_json %>"></div>

<div id="material-top" data-shape-top-params="<%= {materialTop: selectedOptions[0].innerHTML}.to_json %>"></div>

<div id="height-top" data-shape-top-params="<%= {heightTop: selectedOptions[0].innerHTML}.to_json %>"></div>

<div id="width-top" data-shape-top-params="<%= {widthTop: selectedOptions[0].innerHTML}.to_json %>"></div>

<div id="length-top" data-shape-top-params="<%= {lengthTop: selectedOptions[0].innerHTML}.to_json %>"></div>


<div id="shape-bottom" data-shape-bottom-params="<%= {shapeBottom: selectedOptions[0].innerHTML}.to_json %>"></div>

<div id="color-bottom" data-color-bottom-params="<%= {colorBottom: selectedOptions[0].innerHTML}.to_json %>"></div>

<div id="material-bottom" data-material-bottom-params="<%= {materialBottom: selectedOptions[0].innerHTML}.to_json %>"></div>

<div id="height-bottom" data-height-bottom-params="<%= {heightBottom: selectedOptions[0].innerHTML}.to_json %>"></div>

<div id="width-bottom" data-width-bottom-params="<%= {widthBottom: selectedOptions[0].innerHTML}.to_json %>"></div>

<div id="length-bottom" data-length-bottom-params="<%= {lengthBottom: selectedOptions[0].innerHTML}.to_json %>"></div>

app/views/pieces/_quote-card.html.erb
<div class="d-flex justify-content-between">

  <div class="detail-card d-flex justify-content-around align-items-center mt-3">
    <div class="artisan-avatar pl-3">
      <img src="https://kitt.lewagon.com/placeholder/users/joz84" class="avatar-bordered" />
    </div>
    <div class="artisan-info d-flex flex-column justify-content-center align-items-center pr-2">
      <h2 class="pt-3">Artisan : Jojo Seraf'</h2>
      <p><em>" Passionné de bois et de travail manuel, j'aime réaliser des meubles qui répondent aux attentes des clients "</em></p>
      <p>Bordeaux - 33000</p>
      <div class="d-flex"><p>5/5 (27 avis)<ul class="rating-star">
        <li><i class="fas fa-star"></i></li>
        <li><i class="fas fa-star"></i></li>
        <li><i class="fas fa-star"></i></li>
        <li><i class="fas fa-star"></i></li>
        <li><i class="fas fa-star"></i></li>
      </ul></p></div>
    </div>
  </div>

  <div class="detail-card mt-3 d-flex flex-column justify-content-center align-items-center">
    <h2>Le prix estimé de votre objet est de :<br>
      <span class="price">350€*</span></h2>
      <p><em>*Sous réserve de modification lors de la validation du devis par l'artisan</em></p>
    <div class="d-flex">
      <%= link_to "Commander", piece_orders_path(@piece), method: :post, :class => "btn btn-info mr-3" %>
      <%= link_to "Annuler", piece_path, :class => "btn btn-primary ml-3" %>
    </div>
  </div>

</div>

app/views/pieces/edit.html.erb
<div class="text-center border-bottom border-top py-5 bg-white">
  <h2>Mon espace de création</h2>
</div>

<% if !@copy_piece.nil? %>
  <%= @copy_piece.parts %>
<% end %>

<div class="fat-container">

  <div id="container">
      <canvas id="c" data-piece-params="<%= @piece.json_params.to_json %>"></canvas>
  </div>

  <div id="form-user">
    <%= link_to "Enregistrer pour plus tard", dashboard_path, class: "btn btn-primary px-4 mt-3 btn-fix-color" %>
    <h4 class = "pt-4">Plateau</h4>
    <div class="form-edit mt-2 mb-3">
      <%= simple_form_for @part_top, url: part_path(@part_top), method: :patch do |f| %>
        <div class="d-flex align-items-center w-100 input-form-edit">
          <div class="pr-5">Forme<span class="text-white">s</span></div>
          <div class="w-100">
            <%= f.input :shape, collection: Part.shapes.keys, input_html: {class: "shape-top"}, label: false %>
          </div>
        </div>

        <div class="d-flex align-items-center w-100 input-form-edit">
          <div class="pr-5">Couleur</div>
          <div class="w-100">
            <%= f.input :color, collection: Part.colors.keys, input_html: {class: "color-top"}, label: false %>
          </div>
        </div>

        <div class="d-flex align-items-center w-100 input-form-edit">
          <div class="w-20 pr-3 py-2">
            <div class="mb-2">Epaisseur</div>
            <%= f.input :height, input_html: {class: "height-top"}, label: false %>
          </div>
          <div class="w-20 pr-3 py-2">
            <div class="mb-2">Largeur</div>
            <%= f.input :width, input_html: {class: "width-top"}, label: false %>
          </div>
          <div class="w-20 py-2">
            <div class="mb-2">Longueur</div>
            <%= f.input :length, input_html: {class: "length-top"},label: false %>
          </div>
        </div>
        <%= f.submit "continuer", class: 'btn btn-flat' %>
      <% end %>
    </div>

    <h4>Pieds de table</h4>
    <div class="form-edit my-3">
      <%= simple_form_for @part_bottom, url: part_path(@part_bottom), method: :patch do |f| %>
        <div class="d-flex align-items-center w-100 input-form-edit">
          <div class="pr-5">Forme<span class="text-white">s</span></div>
          <div class="w-100">
            <%= f.input :shape, collection: Part.shapes.keys, input_html: {class: "shape-bottom"}, label: false %>
          </div>
        </div>
        

        <div class="d-flex align-items-center w-100 input-form-edit">
          <div class="pr-5">Couleur</div>
          <div class="w-100">
            <%= f.input :color, collection: Part.colors.keys, input_html: {class: "color-bottom"}, label: false %>
          </div>
        </div>

        <div class="d-flex align-items-center w-100 input-form-edit">
          <%# <div class="w-20 pr-3">
            <div class="mb-2">Hauteur</div>
            <%= f.input :height, input_html: {class: "height-bottom"}, label: false %>
          <%# </div> %>
          <div class="w-20 pr-3">
            <div class="mb-2">Diamètre</div>
            <%= f.input :width, input_html: {class: "width-bottom"}, label: false %>
          </div>
          <div class="w-20">
            <div class="mb-2">Longueur</div>
            <%= f.input :length, input_html: {class: "length-bottom"},label: false %>
          </div>
        </div>
        <%= f.submit "continuer", class: 'btn btn-flat'%>
      <% end %>
    </div>

    <h4> Nom de l'objet</h4>
    <div class="form-name mt-3">
      <%= simple_form_for @piece do |f| %>
        <div class="name">
          <%= f.input :name, label: false %>
        </div>
        <div class="d-flex justify-content-between validation">
          <%= f.submit "valider", class: "btn-flat btn-info" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/pieces/index.html.erb
<div class="text-center border-bottom border-top py-5 bg-white">
  <h2>Découvrez nos créations</h2>
</div>
<div class="container pt-2 text-center">
  <div class="pieces-index">
    <div class="card-group">
      <div class="row">
        <% @pieces.each do |piece| %>
          <div class="col-4">
              <div class="card card-index my-5 team__link" style="width: 20rem;">
                <%= cl_image_tag piece.photo.key, class: "card-img-top", :width=>360, :height=>250, :crop=>"fill" %>
                <div class="card-body team__text">
                  <h5 class="team__title"><%= link_to "#{piece.name}", piece_path(piece), class:"effect-underline"%></h5>
                  <p class="text-center pt-2"> <%= piece.description %></p>
                </div>
              </div>
          </div>
        <% end%>
      </div>
    </div>
  </div>
</div>

app/views/pieces/show.html.erb
<div class="container">

  <h1 class="mt-3"><%= @piece.category.title.capitalize %> <small>></small></h1>

    <div class="cont-all mt-3 d-flex justify-content-between">
      <div class="card-img-show">
        <% if @piece.photo.attached? %>
          <%= cl_image_tag @piece.photo.key, :width=>500, :height=>350, :crop=>"fill", class: "card-img-top zoom"%>
        <% else %>
          <%= cl_image_tag "mv2lqq", :width=>500, :height=>350, :crop=>"fill", class: "card-img-top zoom"%>
        <% end %>
      </div>
      <div class="card-inner pl-3 mx-5">
        <h2 class="pb-2"><%= @piece.name.capitalize %></h2>
        <% if !@editable %>
        <div class="inner-desc my-3"><em><%= @piece.description %></em></div>
        <% else %>
        <div class="inner-desc my-3"><em>Caractéristiques de votre table :</em></div>
        <% end %>
          <div class="inner-text d-flex justify-content-around">
            <div class="mt-3">
              <p><strong>Plateau :</strong></p>
              <p><u>Couleur :</u> <%= @top.translated_color %><br>
                <u>Dimension :</u> <%= @top.length %>x<%= @top.width %>x<%= @top.height %><br>
                <u>Matériau :</u> <%= @top.translated_material %><br>
                <u>Forme :</u> <%= @top.translated_shape %></p>
            </div>
            <div class="mt-3">
              <p><strong>Pieds :</strong></p>
              <p><u>Couleur :</u> <%= @bottom.translated_color %><br>
                <u>Dimension :</u> <%= @bottom.length %>x<%= @bottom.width %>x<%= @bottom.height %><br>
                <u>Matériau :</u> <%= @bottom.translated_material %><br>
                <u>Forme :</u> <%= @bottom.translated_shape %></p>
            </div>
          </div>
            <% if !@editable %>
              <div class="inner-button d-flex justify-content-center mt-4">
                <%= link_to "Partir de ce modèle", pieces_path(id: @piece.id), method: :post, :class => "btn btn-primary px-4 mt-3 btn-fix-color" %>
              </div>
            <% end %>
      </div>
    </div>


  <% if @editable %>
    <%= render "quote-card" %>
  <% end %>

</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="header-container">
    <h1>WOODSTOCK</h1>
    <p>Créez le meuble de vos envies</p>

    <%# <%= link_to "Je me lance", category_pieces_path(category_id: 36, piece: {name: 'test ta', category_id: 36 }), method: :post, :class => "btn btn-flat btn-info ml-10 sweet-alert" %>

    <button type="button" class="btn btn-flat btn-info ml-10" data-bs-toggle="modal" data-bs-target="#categoryModal">
      Je me lance !
    </button>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="categoryModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Choisissez une catégorie :</h5>
      </div>
      <div class="modal-body d-flex justify-content-center">
        <div class="row">
          <% @categories.each do |category| %>
            <div class="col-4 mb-3 d-flex justify-content-center">
              <%= link_to category.title, category_pieces_path(category), method: :post, :class => "checklist px-3 py-1" %>
            </div>
          <% end -%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">Woodstock - 2021 ©</div>
</div>